### ISSUE TITLE
Questions about Reaasemble Files

### ISSUE THREAD

**Issue by Ohuoa1** [CPJKU/cpjku_dcase22#2]
![微信图片_20220809103611](https://user-images.githubusercontent.com/110874956/183551329-f48411a4-43fe-4c06-9fbf-ebdd3e09f1e2.png)
Hello, recently when reproducing your code, it shows "adapt and copy also meta.csv and evaluation_setup folder to created reassembled dataset..."
I want to know if I copy the official meta.csv and evaluation_setup folder here, or do I need to generate a new one based on the generated audio?
Looking forward to your answer, your answer will be of great help to me.

**Comment by fschmid56** [comment]
You need to generate a new 'meta.csv' file and the '/evaluation_setup' folder. This can be done using a simple script. 

However, since the _TAU Urban Acoustic Scenes 2020 Mobile, Development dataset_ is in fact only a reassembled version of the _TAU Urban Acoustic Scenes 2022 Mobile, Development dataset_ (with very minor differences), you can probably just download the metadata files from here: https://zenodo.org/record/3819968/files/TAU-urban-acoustic-scenes-2020-mobile-development.meta.zip?download=1.

**Comment by Noumanijaz744** [comment]
while reproducing your code i am getting error because of meta.csv and audio samples have some files missing.

[Errno 2] No such file or directory: '/data/nouman/datasets/d22/TAU-urban-acoustic-scenes-2022-mobile-development/audioaudio/shopping_mall-lyon-1043-43866-0-a.wav

i hope you will help me how to solve this problem?
